In [2]:
# check head of both crime_final_gdf.gpkg and walkability_final_gdf.gpkg
import geopandas as gpd
crime_gdf = gpd.read_file("../data/processed/crime_final_gdf.gpkg")
walkability_gdf = gpd.read_file("../data/processed/walkability_final_gdf.gpkg")
display(crime_gdf.head())
display(walkability_gdf.head())

,INCIDENT_NUM,DATE_TIME,DAY_OF_WEEK,ADDRESS_ROAD_PRIMARY,CALL_TYPE,DISPOSITION,PRIORITY,HOUR,geometry
0,E26040027846,2026-04-20 10:48:53,2,EL CAJON,415V,R,1,10,POINT (-117.06696 32.76148)
1,E26040027876,2026-04-20 11:07:54,2,C,242,R,1,11,POINT (-117.16002 32.71684)
2,E26040027882,2026-04-20 11:10:22,2,HOTEL CIRCLE SOUTH,415V,R,1,11,POINT (-117.17811 32.7589)
3,E26040027891,2026-04-20 11:15:24,2,LANDIS,242R,R,2,11,POINT (-117.12218 32.74549)
4,E26040028068,2026-04-20 13:20:46,2,AIR,415V,O,1,13,POINT (-117.09512 32.71952)

,GEOID,CBSA,CBSA_Name,TotPop,NatWalkInd,geometry
0,060730027122,41740.0,"San Diego-Chula Vista-Carlsbad, CA",1653,13.500000,"POLYGON ((-117.08306 32.72588, -117.0828 32.72..."
1,060730186012,41740.0,"San Diego-Chula Vista-Carlsbad, CA",3958,5.333333,"POLYGON ((-117.35296 33.22489, -117.35294 33.2..."
2,060730186093,41740.0,"San Diego-Chula Vista-Carlsbad, CA",2376,13.000000,"POLYGON ((-117.31819 33.25084, -117.31819 33.2..."
3,060730194063,41740.0,"San Diego-Chula Vista-Carlsbad, CA",1485,6.500000,"POLYGON ((-117.2737 33.19762, -117.27367 33.19..."
4,060730195032,41740.0,"San Diego-Chula Vista-Carlsbad, CA",1079,16.333333,"POLYGON ((-117.24344 33.20156, -117.24329 33.2..."